trigger:
  batch: true
  branches:
    include:
    - main
    - release/3.x
    - release/5.0
    - release/6.0
    - release/7.0
pr:
  branches:
    include:
    - main
    - release/3.x
    - release/5.0
    - release/6.0
    - release/7.0
    - templates

variables:
- template: /eng/common-variables.yml
- template: /eng/common/templates/variables/pool-providers.yml

resources:
  containers:
  - container: LinuxContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7

stages:
- stage: build
  displayName: Build
  jobs:
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
    - template: /eng/common/templates/job/onelocbuild.yml
      parameters:
        MirrorRepo: arcade
        LclSource: lclFilesFromPackage
        LclPackageId: 'LCL-JUNO-PROD-ARCADE'
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      artifacts:
        publish:
          artifacts: false
          logs: false
          manifests: false
      enableMicrobuild: true
      enablePublishUsingPipelines: true
      enableSourceIndex: false
      enableSourceBuild: false
      workspace:
        clean: all
      jobs:
      - ${{ if eq(variables._RunAsPublic, True) }}:
        - job: netcore_public
          pool:
            name: netcore-public
            demands: ImageOverride -equals build.ubuntu.2204.amd64.open
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore_public_int
          pool:
            name: netcore-public-int
            demands: ImageOverride -equals build.ubuntu.2204.amd64.open
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore_public_xl
          pool:
            name: netcore-public-xl
            demands: ImageOverride -equals build.ubuntu.2204.amd64.open
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore_public_xl_int
          pool:
            name: netcore-public-xl-int
            demands: ImageOverride -equals build.ubuntu.2204.amd64.open
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore_svc_public
          pool:
            name: netcore-svc-public
            demands: ImageOverride -equals build.ubuntu.2204.amd64.open
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore_svc_public_int
          pool:
            name: netcore-svc-public-int
            demands: ImageOverride -equals build.ubuntu.2204.amd64.open
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
      - ${{ if eq(variables._RunAsInternal, True) }}:
        - job: netcore1espool_internal
          pool:
            name: netcore1espool-internal
            demands: ImageOverride -equals build.ubuntu.2204.amd64
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore1espool_internal_int
          pool:
            name: netcore1espool-internal-int
            demands: ImageOverride -equals build.ubuntu.2204.amd64
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore1espool_internal_nomsi
          pool:
            name: netcore1espool-internal-nomsi
            demands: ImageOverride -equals build.ubuntu.2204.amd64
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore1espool_internal_nomsi_int
          pool:
            name: netcore1espool-internal-nomsi-int
            demands: ImageOverride -equals build.ubuntu.2204.amd64
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore1espool_internal_xl
          pool:
            name: netcore1espool-internal-xl
            demands: ImageOverride -equals build.ubuntu.2204.amd64
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore1espool_internal_xl_int
          pool:
            name: netcore1espool-internal-xl-int
            demands: ImageOverride -equals build.ubuntu.2204.amd64
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore1espool_svc_internal
          pool:
            name: netcore1espool-svc-internal
            demands: ImageOverride -equals build.ubuntu.2204.amd64
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
        - job: netcore1espool_svc_internal_int
          pool:
            name: netcore1espool-internal-xl-int
            demands: ImageOverride -equals build.ubuntu.2204.amd64
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration debug
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
      