trigger:
  batch: true
  branches:
    include:
    - main
    - release/3.x
    - release/5.0
    - release/6.0
    - release/7.0
pr:
  branches:
    include:
    - main
    - release/3.x
    - release/5.0
    - release/6.0
    - release/7.0
    - templates

variables:
- template: /eng/common-variables.yml
- template: /eng/common/templates/variables/pool-providers.yml

resources:
  containers:
  - container: LinuxContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7

stages:
- stage: build
  displayName: Build
  jobs:
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
    - template: /eng/common/templates/job/onelocbuild.yml
      parameters:
        MirrorRepo: arcade
        LclSource: lclFilesFromPackage
        LclPackageId: 'LCL-JUNO-PROD-ARCADE'
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      artifacts:
        publish:
          artifacts: false
          logs: false
          manifests: false
      enableMicrobuild: true
      enablePublishUsingPipelines: true
      enableSourceIndex: false
      enableSourceBuild: false
      workspace:
        clean: all
      jobs:
      - ${{ if eq(variables._RunAsPublic, True) }}:
        - job: es_ubuntu_2004_open
          pool:
            name: $(DncEngPublicBuildPool)
            demands: ImageOverride -equals 1es-ubuntu-2004-open
          strategy:
            matrix:
              Build_Debug:
                _BuildConfig: Debug
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: df -h
            displayName: disk space before build
          - script: eng/common/cibuild.sh
              --configuration $(_BuildConfig)
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
          - script: df -h
            displayName: disk space after build
        - job: es_ubuntu_1804_open
          pool:
            name: $(DncEngPublicBuildPool)
            demands: ImageOverride -equals 1es-ubuntu-1804-open
          strategy:
            matrix:
              Build_Debug:
                _BuildConfig: Debug
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: df -h
            displayName: disk space before build
          - script: eng/common/cibuild.sh
              --configuration $(_BuildConfig)
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
          - script: df -h
            displayName: disk space after build
        - job: build_ubuntu_2004_amd64_open
          pool:
            name: $(DncEngPublicBuildPool)
            demands: ImageOverride -equals build.ubuntu.2004.amd64.open
          strategy:
            matrix:
              Build_Debug:
                _BuildConfig: Debug
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: df -h
            displayName: disk space before build
          - script: eng/common/cibuild.sh
              --configuration $(_BuildConfig)
              --prepareMachine
              /p:Test=false
            displayName: Unix Build / Publish
          - script: df -h
            displayName: disk space after build
